NEW: Locale fallback configuration enhancement.
tractorcow-farm/silverstripe-fluent pull request #711
Opened 2021-05-20 00:37 UTC by mfendeksilverstripe

# NEW: Locale fallback configuration enhancement

* Fallback option added to both 

Fix for https://github.com/tractorcow-farm/silverstripe-fluent/issues/705

2021-05-20 01:22 UTC, tractorcow commented on src/Extension/FluentExtension.php
> +            foreach ($this->owner->getLocalisedTables() as $table => $fields) {
instead of all tables, can we just use the base table please for each locale?

2021-05-20 01:23 UTC, tractorcow commented on src/Extension/FluentExtension.php
> +        $inheritanceMode = FluentState::singleton()->getIsFrontend()
I suggest we detect is_boolean here, and map to the default values. It doesn't have to be a deprecation warning.

E.g. false == none, true === fallback

2021-05-20 01:24 UTC, tractorcow requested changes
as commented

2021-05-20 01:26 UTC, tractorcow commented on src/Extension/FluentExtension.php
> +    const INHERITANCE_MODE_NONE = 'none';
I feel like 'none' is a bit obtuse. How about "exact"? (no fallback, must be localised in exact locale)

2021-05-20 01:28 UTC, tractorcow commented on _config/model.yml
> +  frontend_publish_required: none
Since this is master (new major version) happy to change default to `fallback` to give the best out of the box for the frontend.

2021-05-20 01:29 UTC, tractorcow commented
@mfendeksilverstripe great job :D

2021-05-20 02:36 UTC, mfendeksilverstripe commented
Thanks for feedback @tractorcow , I've pushed the requested changes, please review.

2021-05-20 23:25 UTC, tractorcow approved these changes

2021-05-20 23:25 UTC, merged

2021-05-20 23:26 UTC, tractorcow commented
@mfendeksilverstripe think we need a 6.0.0 tag, or still more breaking changes to go in? (Gut feel says it's a bit early)

2021-05-20 23:31 UTC, mfendeksilverstripe commented
I recommend waiting a bit @tractorcow as I have some more items on my list to go trough.

2021-05-21 02:42 UTC, tractorcow commented
@mfendeksilverstripe also, I don't mind this not being in 5.1 also (in a non-breaking way) but I can back-port it if someone really wants it.