TLN Update translations
tractorcow-farm/silverstripe-fluent pull request #822
Opened 2024-02-06 23:34 UTC by GuySartorelli

Automated translations update generated using [silverstripe/tx-translator](https://github.com/silverstripe/silverstripe-tx-translator)

2024-02-07 03:16 UTC, emteknetnz requested changes
JS diff failed

2024-02-07 20:11 UTC, GuySartorelli commented
JS CI failure is unrelated to the changes in this PR

2024-02-07 20:35 UTC, emteknetnz approved these changes

2024-02-08 00:33 UTC, GuySartorelli commented
Self-merging as another core committer has approved.

2024-02-08 00:33 UTC, merged