ENH: Explicit configuration API properties.
tractorcow-farm/silverstripe-fluent pull request #841
Opened 2024-04-08 04:19 UTC by mfendeksilverstripe

# ENH: Explicit configuration API properties.

## Description

* Added explicit configuration API properties for existing settings
* Minor code refactor for tests (DRY code cleanup)
* No functional changes overall

## Pull request checklist
- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

2024-04-08 04:43 UTC, mfendeksilverstripe commented
Hey @GuySartorelli , need some guidance with this one as this is technically just a code refactor with no functional changes. I did add new configuration API properties but these are for existing settings.

2024-04-08 04:52 UTC, GuySartorelli commented
Yup no problem. What guidance are you after specifically?

2024-04-08 19:12 UTC, mfendeksilverstripe commented
This is a non-functional code refactor change-set. Which base branch should be used @GuySartorelli ?

2024-04-08 20:57 UTC, GuySartorelli commented
Refactors should target the next minor release (so `7` in this case)

2024-05-07 20:58 UTC, tractorcow commented on src/Extension/FluentFilteredExtension.php
> +    private static bool $apply_filtered_locales_to_stage = false;
Should this be true by default. Otherwise it may be unintuitive if you have a visible (but draft) page that magically can't publish?

2025-02-04 00:59 UTC, GuySartorelli commented
@mfendeksilverstripe Sorry it's taken so long to look at this - can you please rebase it to resolve the merge conflict?

2025-02-04 04:15 UTC, mfendeksilverstripe commented
I've completed the rebase @GuySartorelli , please review.

2025-02-04 20:39 UTC, GuySartorelli requested changes

2025-02-04 20:39 UTC, GuySartorelli commented on src/Extension/FluentExtension.php
> + * @property DataObject|$this $owner
```suggestion
```
There are already generics set up for this, which is what the `@template` and `@extends` are for.

2025-02-04 20:39 UTC, GuySartorelli commented on src/Extension/FluentExtension.php
> +    private static string $frontend_publish_required = FluentExtension::INHERITANCE_MODE_FALLBACK;
```suggestion
     * Fluent inheritance mode for CMS context
     */
    private static string $cms_localisation_required = FluentExtension::INHERITANCE_MODE_ANY;

    /**
     * Fluent inheritance mode for frontend context
     */
    private static string $frontend_publish_required = FluentExtension::INHERITANCE_MODE_FALLBACK;
```
`@config` doesn't do anything, and we don't need typehints in the PHPDoc when we're using strong typing on the property itself.

2025-02-04 20:39 UTC, GuySartorelli commented on src/Extension/FluentFilteredExtension.php
> +    private static bool $apply_filtered_locales_to_stage = false;
```suggestion
     * Allow the filtered locale behaviour to be skipped for draft stage only
     */
    private static bool $apply_filtered_locales_to_stage = false;
```

2025-02-04 20:39 UTC, GuySartorelli commented on tests/php/Extension/FluentFilteredExtensionTest.php
> +        SiteTree::config()->set('apply_filtered_locales_to_stage', true);
Why is this swapping from being applied to `DataObject` to now being applied to `SiteTree` specifically?

2025-02-04 20:39 UTC, GuySartorelli commented on tests/php/Extension/FluentFilteredExtensionTest.php
> +        SiteTree::config()->set('apply_filtered_locales_to_stage', true);
Same question for other changes blow.

2025-02-04 20:39 UTC, GuySartorelli commented on tests/php/Extension/FluentSiteTreeExtensionTest.php
Can you please give me a quick description and reason for the changes in this test class? That will be much quicker than me reading both the old and new tests and trying to figure out what's changing and why.

2025-02-04 20:39 UTC, GuySartorelli commented on src/Extension/FluentExtension.php
Are these intended to replace the same configuration currently added through `_config/model.yml`? If so, would it be prudent to remove that YAML configuration?

2025-02-04 20:39 UTC, GuySartorelli commented on src/Extension/FluentFilteredExtension.php
> +    private static bool $apply_filtered_locales_to_stage = false;
This is set to `true` in `_config/model.yml` - is it correct to change it here? If so, why?

2025-02-06 22:35 UTC, mfendeksilverstripe commented on tests/php/Extension/FluentFilteredExtensionTest.php
> +        SiteTree::config()->set('apply_filtered_locales_to_stage', true);
The test is for `SiteTree`, hence I used `SiteTree` config. Functionally doesn't matter, it just makes the config scope change fit the test.

2025-02-06 22:36 UTC, mfendeksilverstripe commented on tests/php/Extension/FluentSiteTreeExtensionTest.php
No functional changes in the tests - only switching a lot of copy pasted code to use data provides to make it more readable. DRY code cleanup bascially.

2025-02-06 22:39 UTC, mfendeksilverstripe commented on src/Extension/FluentFilteredExtension.php
> +    private static bool $apply_filtered_locales_to_stage = false;
It's either a mistake or an upstream change. Either way it needs to match the `model.yml`. Will make the change.

2025-02-06 22:43 UTC, mfendeksilverstripe commented
@GuySartorelli I've pushed up new changes, please review (PR feedback).

2025-02-09 20:29 UTC, GuySartorelli requested changes
Just a couple of small changes left. Sorry I didn't notice these last review.

2025-02-09 20:29 UTC, GuySartorelli commented on tests/php/Extension/FluentSiteTreeExtensionTest.php
> +    public function localeInheritanceModeCasesProvider(): array
```suggestion
    public function provideLocaleInheritanceMode(): array
```
As per [the coding standards](https://docs.silverstripe.org/en/5/contributing/coding_conventions/php_coding_conventions/#unit-testing)

I wouldn't have bothered with this except there are other changes to make here as well, so makes sense to do this at the same time

2025-02-09 20:29 UTC, GuySartorelli commented on tests/php/Extension/FluentSiteTreeExtensionTest.php
> +                true,
```suggestion
                'cmsInheritanceMode' => FluentExtension::INHERITANCE_MODE_ANY,
                'frontendInheritanceMode' => FluentExtension::INHERITANCE_MODE_ANY,
                'frontendContext' => true,
                'expected' => true,
```
This is needed for PHPUnit 11 which is used in CMS 6 - so doing this now means less work on merge up to the `8.0` branch.
It also makes it immediately clear what each argument is for, which is useful if one of these scenarios starts failing unexpectedly.

Please make this change to all of the scenarios in this provider.

2025-02-09 20:53 UTC, mfendeksilverstripe commented
Have added new changes as per your suggestion, please review @GuySartorelli

2025-02-09 21:09 UTC, GuySartorelli commented
CI failures are due to a problem with the way we set up our CI matrix and not a reflection of failures this PR creates.
I'll set up a separate CI run to check the tests all go green before merging.

2025-02-09 21:48 UTC, GuySartorelli approved these changes
LGTM, CI is green (see link above)

2025-02-09 21:48 UTC, merged

2025-02-09 21:49 UTC, GuySartorelli commented
PR merged.
Please remember that the colon after the commit message prefix isn't needed - and please use a fork for your PR next time. I think that might be at least part of why the CI run didn't work.