FIX Preview link when no locale set
tractorcow-farm/silverstripe-fluent pull request #861
Opened 2024-06-10 00:58 UTC by emteknetnz

Issue https://github.com/silverstripe/.github/issues/272

Fixes vendor/silverstripe/cms/tests/behat/features/preview-a-page.feature:12 - which breaks when silverstripe/recipe-kitchen-sink is run including silverstripe/cms behat tests.

The issue that behat is running into is that the preview link will not show anything as no locale has been defined in a behat context

2024-06-10 04:57 UTC, GuySartorelli requested changes
This is starting to feel really flaky.

I've done a root cause analysis and [this PR](https://github.com/tractorcow-farm/silverstripe-fluent/pull/781) is what causes the problem that results in needing this "temp locale" in the first place.

This fixes it without needing a temp locale:
```diff
     public function updatePreviewLink(&$link): void
     {
         $owner = $this->owner;
-        $info = $owner->LocaleInformation(FluentState::singleton()->getLocale());
+        $locale = FluentState::singleton()->getLocale();
+        if ($locale === null || $locale === '') {
+            return;
+        }
+        $info = $owner->LocaleInformation($locale);

         if (!$info->getSourceLocale()) {
             $link = null;
         }
     }
```

2024-06-10 21:42 UTC, emteknetnz commented
Updated

2024-06-10 22:53 UTC, GuySartorelli requested changes
Should also revert the changes that were made in https://github.com/tractorcow-farm/silverstripe-fluent/pull/860/commits/2714bff77c5baebcabf63e5aa281be57f9b05dbf and https://github.com/tractorcow-farm/silverstripe-fluent/pull/860/commits/b14687a9d09eb8ad8ef54c722e87895e4d256939 - the temporary locale isn't needed anymore.

2024-06-10 23:33 UTC, emteknetnz commented
Surprisingly yes, looks like the previous CI failure was actually just from rendering the preview link from a template.

Reverted as second commit, so do not squash merge

2024-06-11 00:09 UTC, GuySartorelli approved these changes
LGTM

2024-06-11 00:09 UTC, merged