API Update API to reflect changes to CLI interaction
tractorcow-farm/silverstripe-fluent pull request #884
Opened 2024-09-06 03:10 UTC by GuySartorelli

Reflects changes in https://github.com/silverstripe/silverstripe-framework/pull/11353

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/11341

2024-09-06 03:13 UTC, GuySartorelli commented on src/Task/ConvertTranslatableTask.php
Removed this because the translatable module hasn't been a thing for a really long time - it's time to remove this task.

2024-09-18 21:43 UTC, tractorcow approved these changes

2024-09-18 21:44 UTC, tractorcow commented
Approved, but pending build to pass.

```
PHP Fatal error:  Type of TractorCow\Fluent\Task\InitialDataObjectLocalisationTask::$title must not be defined (as in class SilverStripe\Dev\BuildTask) in /home/runner/work/silverstripe-fluent/silverstripe-fluent/src/Task/InitialDataObjectLocalisationTask.php on line 20
```

2024-09-18 21:46 UTC, GuySartorelli commented
This PR (and it'll be the case with most of the CMS 6 PRs) relies on code in other PRs. They'll all need to be merged together.

2024-09-26 05:26 UTC, emteknetnz approved these changes

2024-09-26 05:37 UTC, emteknetnz requested changes
Unit test failures

2024-09-26 21:05 UTC, GuySartorelli commented
CI failures don't look related to the changes in this PR - running a regular CI run to see if it fails the same way. https://github.com/tractorcow-farm/silverstripe-fluent/actions/runs/11060232590

2024-09-26 21:11 UTC, GuySartorelli commented
Main CI isn't even getting that far.
I recommend we merge and then clean up CI in a broken builds card.

2024-09-26 21:59 UTC, emteknetnz approved these changes

2024-09-26 22:00 UTC, merged