ENH Update status flags generally, not just for SiteTree
tractorcow-farm/silverstripe-fluent pull request #909
Opened 2024-11-20 02:49 UTC by GuySartorelli

https://github.com/silverstripe/silverstripe-framework/pull/11460 makes the `updateStatusFlags()` extension hook available for all models. In combination with other PRs linked in the below issue, status flag rendering has now been standardised.

This PR updates fluent to add fluent status flags to any fluent model, not just `SiteTree`, and removes custom code that renders flags in places like `LeftAndMain` breadcrumbs, gridfield edit form breadcrumbs, and gridfield rows. Those are all handled in core now.

Please note that this PR relies on https://github.com/silverstripe/silverstripe-framework/pull/11460 along with others. **_Please do not merge this PR until all dependent PRs have been merged._**

## Issue
- https://github.com/silverstripe/silverstripe-cms/issues/2947

2024-11-20 02:50 UTC, GuySartorelli commented on src/Extension/FluentSiteTreeExtension.php
> -    protected function updateStatusFlags(&$flags)
Nothing here is specific to SiteTree anymore. This is now split up between `FluentExtension` and `FluentVersionedExtension` along with the methods called from here.

2024-11-20 02:50 UTC, GuySartorelli commented on src/Extension/FluentExtension.php
> +    protected function updateStatusFlags(array &$flags): void
See `FluentSiteTreeExtension` for where this code originated.

2024-11-20 02:50 UTC, GuySartorelli commented on src/Extension/FluentVersionedExtension.php
> +    protected function updateStatusFlags(array &$flags): void
See `FluentSiteTreeExtension` for where this code originated.

2024-11-20 02:51 UTC, GuySartorelli commented on src/Extension/FluentGridFieldExtension.php
> -    protected function updateBadge(&$badgeField)
That hook doesn't exist anymore - this is now handled through generalised status flag rendering in core.

2024-11-20 02:51 UTC, GuySartorelli commented on src/Extension/FluentLeftAndMainExtension.php
> -    protected function updateBreadcrumbs(ArrayList $breadcrumbs)
This is now handled through generalised status flag rendering in core.

2024-11-26 03:55 UTC, emteknetnz requested changes
I've tried rerunning tests after merging everything else, there are CI failures

2024-11-26 05:12 UTC, GuySartorelli commented
Updated status flag tests and added a little more coverage than was already there.

2024-11-26 06:27 UTC, emteknetnz approved these changes
Seems to do what it's supposed to do

2024-11-26 06:27 UTC, merged